name: Github Hosted Runner

on:
  workflow_dispatch:

jobs:
  hosted-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Display Message
        run: echo "Running on Github Hosted Runner"
      - name: Show current user
        run: whoami
      - name: Show OS
        run: uname -a
      - name: Show Working Directory
        run: pwd
      - name: Display date
        run: date
