name: Manual Workflow

on: workflow_dispatch

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Message
        run: echo "Manual workflow executed successfully"
      - name: Display date
        run: date
