name: Secrets Management

on:
  workflow_dispatch:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    env: MY_SECRET = ${{secrets.PRACTICE_SECRET}}

    steps:
      - name: Get secret length
        run: |
          echo "Secret is configured securely"
          echo "Secret length: ${#MY_SECRET}"
